"""add user_id to tasks

Revision ID: b41d2ac1d8f6
Revises: 419c5aa3c650
Create Date: 2026-06-13 18:47:22.694085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41d2ac1d8f6'
down_revision: Union[str, Sequence[str], None] = '419c5aa3c650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Boolean(),
               postgresql_using='status::boolean',
               nullable=True)
    op.drop_constraint(op.f('fk_tasks_user_id_users'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_user_id_users'), 'tasks', 'users', ['user_id'], ['id'], onupdate='CASCADE')
    op.alter_column('tasks', 'status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
